language: python
python: 2.7
env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py32
    - TOXENV=py34
    - TOXENV=sphinx1.0
    - TOXENV=sphinx1.1
    - TOXENV=sphinx1.2
    - TOXENV=blockdiag_dev
    - TOXENV=coverage

install: pip install docutils tox
script: tox
